version: '1.0'
name: pipeline-test
displayName: pipeline-test
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
    commitMessages:
      include:
        - fix:*
stages:
  - name: stage-6eb79649
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: 89b6edd0-da93-013a-f64e-2a6162a31375
        tag: risv:${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        artifacts: []
        isCache: true
        strategy:
          retry: '0'
  - name: stage-00fbade3
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: 发布
        dependArtifact: output
        version: 1.0.0.0
        autoIncrement: true
        strategy:
          retry: '0'
strategy:
  blocking: false
permissions:
  - role: admin
    members:
      - Etzyio
