version: '1.0'
name: pipeline-20220630
displayName: pipeline-20220630
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-7987a6c2
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: c2d6cdc0-da7b-013a-de23-3a29d97e4f67
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: ./Dockerfile
        artifacts: []
        isCache: true
        strategy:
          retry: '0'
permissions:
  - role: admin
    members: []
